/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "tuplas.h"

bool_t
xdr_Value (XDR *xdrs, Value *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->key))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->value1, 256))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->value2))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->value3))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_TwoKeys (XDR *xdrs, TwoKeys *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->key1))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->key2))
		 return FALSE;
	return TRUE;
}
