/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "tuplas.h"
#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <string.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>

#ifndef SIG_PF
#define SIG_PF void(*)(int)
#endif

int
_init_service_1 (void  *argp, void *result, struct svc_req *rqstp)
{
	return (init_service_1_svc(result, rqstp));
}

int
_set_tuple_1 (set_tuple_1_argument *argp, void *result, struct svc_req *rqstp)
{
	return (set_tuple_1_svc(argp->key, argp->value1, argp->value2, argp->value3, result, rqstp));
}

int
_get_tuple_1 (int  *argp, void *result, struct svc_req *rqstp)
{
	return (get_tuple_1_svc(*argp, result, rqstp));
}

int
_modify_tuple_1 (modify_tuple_1_argument *argp, void *result, struct svc_req *rqstp)
{
	return (modify_tuple_1_svc(argp->key, argp->value1, argp->value2, argp->value3, result, rqstp));
}

int
_delete_tuple_1 (int  *argp, void *result, struct svc_req *rqstp)
{
	return (delete_tuple_1_svc(*argp, result, rqstp));
}

int
_check_existence_1 (int  *argp, void *result, struct svc_req *rqstp)
{
	return (check_existence_1_svc(*argp, result, rqstp));
}

int
_copy_tuple_1 (copy_tuple_1_argument *argp, void *result, struct svc_req *rqstp)
{
	return (copy_tuple_1_svc(argp->key1, argp->key2, result, rqstp));
}

static void
tuple_service_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		set_tuple_1_argument set_tuple_1_arg;
		int get_tuple_1_arg;
		modify_tuple_1_argument modify_tuple_1_arg;
		int delete_tuple_1_arg;
		int check_existence_1_arg;
		copy_tuple_1_argument copy_tuple_1_arg;
	} argument;
	union {
		status init_service_1_res;
		status set_tuple_1_res;
		tuple get_tuple_1_res;
		status modify_tuple_1_res;
		status delete_tuple_1_res;
		status check_existence_1_res;
		status copy_tuple_1_res;
	} result;
	bool_t retval;
	xdrproc_t _xdr_argument, _xdr_result;
	bool_t (*local)(char *, void *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case init_service:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_status;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_init_service_1;
		break;

	case set_tuple:
		_xdr_argument = (xdrproc_t) xdr_set_tuple_1_argument;
		_xdr_result = (xdrproc_t) xdr_status;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_set_tuple_1;
		break;

	case get_tuple:
		_xdr_argument = (xdrproc_t) xdr_int;
		_xdr_result = (xdrproc_t) xdr_tuple;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_get_tuple_1;
		break;

	case modify_tuple:
		_xdr_argument = (xdrproc_t) xdr_modify_tuple_1_argument;
		_xdr_result = (xdrproc_t) xdr_status;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_modify_tuple_1;
		break;

	case delete_tuple:
		_xdr_argument = (xdrproc_t) xdr_int;
		_xdr_result = (xdrproc_t) xdr_status;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_delete_tuple_1;
		break;

	case check_existence:
		_xdr_argument = (xdrproc_t) xdr_int;
		_xdr_result = (xdrproc_t) xdr_status;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_check_existence_1;
		break;

	case copy_tuple:
		_xdr_argument = (xdrproc_t) xdr_copy_tuple_1_argument;
		_xdr_result = (xdrproc_t) xdr_status;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_copy_tuple_1;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	retval = (bool_t) (*local)((char *)&argument, (void *)&result, rqstp);
	if (retval > 0 && !svc_sendreply(transp, (xdrproc_t) _xdr_result, (char *)&result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	if (!tuple_service_1_freeresult (transp, _xdr_result, (caddr_t) &result))
		fprintf (stderr, "%s", "unable to free results");

	return;
}

int
main (int argc, char **argv)
{
	register SVCXPRT *transp;

	pmap_unset (TUPLE_SERVICE, TUPLE_SERVICE_V1);

	transp = svcudp_create(RPC_ANYSOCK);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create udp service.");
		exit(1);
	}
	if (!svc_register(transp, TUPLE_SERVICE, TUPLE_SERVICE_V1, tuple_service_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (TUPLE_SERVICE, TUPLE_SERVICE_V1, udp).");
		exit(1);
	}

	transp = svctcp_create(RPC_ANYSOCK, 0, 0);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create tcp service.");
		exit(1);
	}
	if (!svc_register(transp, TUPLE_SERVICE, TUPLE_SERVICE_V1, tuple_service_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (TUPLE_SERVICE, TUPLE_SERVICE_V1, tcp).");
		exit(1);
	}

	svc_run ();
	fprintf (stderr, "%s", "svc_run returned");
	exit (1);
	/* NOTREACHED */
}
