/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "tuplas.h"


void
tuple_service_1(char *host)
{
	CLIENT *clnt;
	enum clnt_stat retval_1;
	status result_1;
	enum clnt_stat retval_2;
	status result_2;
	int set_tuple_1_key;
	char *set_tuple_1_value1;
	int set_tuple_1_value2;
	double set_tuple_1_value3;
	enum clnt_stat retval_3;
	tuple result_3;
	int get_tuple_1_key;
	enum clnt_stat retval_4;
	status result_4;
	int modify_tuple_1_key;
	char *modify_tuple_1_value1;
	int modify_tuple_1_value2;
	double modify_tuple_1_value3;
	enum clnt_stat retval_5;
	status result_5;
	int delete_tuple_1_key;
	enum clnt_stat retval_6;
	status result_6;
	int check_existence_1_key;
	enum clnt_stat retval_7;
	status result_7;
	int copy_tuple_1_key1;
	int copy_tuple_1_key2;

#ifndef	DEBUG
	clnt = clnt_create (host, TUPLE_SERVICE, TUPLE_SERVICE_V1, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	retval_1 = init_service_1(&result_1, clnt);
	if (retval_1 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}
	retval_2 = set_tuple_1(set_tuple_1_key, set_tuple_1_value1, set_tuple_1_value2, set_tuple_1_value3, &result_2, clnt);
	if (retval_2 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}
	retval_3 = get_tuple_1(get_tuple_1_key, &result_3, clnt);
	if (retval_3 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}
	retval_4 = modify_tuple_1(modify_tuple_1_key, modify_tuple_1_value1, modify_tuple_1_value2, modify_tuple_1_value3, &result_4, clnt);
	if (retval_4 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}
	retval_5 = delete_tuple_1(delete_tuple_1_key, &result_5, clnt);
	if (retval_5 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}
	retval_6 = check_existence_1(check_existence_1_key, &result_6, clnt);
	if (retval_6 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}
	retval_7 = copy_tuple_1(copy_tuple_1_key1, copy_tuple_1_key2, &result_7, clnt);
	if (retval_7 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	tuple_service_1 (host);
exit (0);
	}
